<?php

namespace rgen3\product\backend\controllers;

use yii\web\Controller;

class BaseController extends Controller
{
    protected static $templates = [];

    protected function getTemplate($action)
    {
        $template = $action;
        if (isset(self::$templates[$action]))
        {
            $template = self::$templates[$action];
        }

        return $template;
    }

    public function beforeAction($action)
    {
        self::$templates = array_merge(self::$templates, static::$templates);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}