<?php

namespace rgen3\product\backend;

use yii\i18n\PhpMessageSource;

class Module extends \yii\base\Module
{
    public $defaultRoute = 'item';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->setAliases(['@product/common' => __DIR__ . '/../common']);


        return $this->registerTranslation();
    }

    public function registerTranslation()
    {

        \Yii::$app->i18n->translations['rgen3/product/backend/*'] = [
            'class' => PhpMessageSource::class,
            'sourceLanguage' => \Yii::$app->sourceLanguage,
            'basePath' => '@product/common/messages',
            'fileMap' => [
                'rgen3/product/backend/product' => 'item.php'
            ]
        ];
    }

    public static function t($category, $message, $params = [], $language = null)
    {
        return \Yii::t('rgen3/product/backend/' . $category, $message, $params, $language);
    }
}